language: php
php:
  - 5.4
services:
  - memcached
before_script:
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - phpenv config-add travis-php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;

